version: '3.8'

services:
  cosmosdb-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 1
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    ports:
      - "8081:8081"
      - "10250:10250"
    volumes:
      - cosmosdbdata:/data
    networks:
      - mynetwork

  ping_listener:
    build:
      context: ./ping_listener
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - cosmosdb-emulator
      - ping_listener
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  cosmosdbdata:
