version: '3.8'

services:
  cosmosdb-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 1
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    ports:
      - "8081:8081"
      - "10250:10250"
    volumes:
      - cosmosdbdata:/data
    networks:
      - mynetwork
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - cosmosdb-emulator
    environment:
      - CosmosDb__EndpointUri=https://cosmosdb-emulator:8081
      - CosmosDb__PrimaryKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  cosmosdbdata:
